FROM node:18.6-alpine as builder
WORKDIR /app
COPY package.json /app/package.json
RUN npm install --omit=dev
COPY . /app
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
